In [1]:
import numpy


In [8]:
A = numpy.matrix([[1,2,3],[4,5,6],[7,8,9]])
B = numpy.transpose(A)
print(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [9]:
N = numpy.matrix([[2,-1,5],[6,8,0],[-3,7,-1]])
N_T = numpy.transpose(N)
print(N_T)

[[ 2  6 -3]
 [-1  8  7]
 [ 5  0 -1]]


In [10]:
B = numpy.matrix([[1,2,4,0],[2,1,7,6]])
B_T = numpy.transpose(B)
print(B_T)

[[1 2]
 [2 1]
 [4 7]
 [0 6]]


In [16]:
# https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.optimize.linprog.html

from scipy.optimize import linprog

# coefficients of objective function
z = [-6,-3] 

# coefficients of the left-hand side of the inequalities
lhs = [[1,2],[3,1]]

# coefficients of the right-hand side of the inequalities
rhs = [3, 2]

# set the bounds for the variables
x1_bounds = (0, None)
x2_bounds = (0, None)

method='simplex'

res = linprog(c=z, A_ub=lhs, b_ub=rhs,  bounds=(x1_bounds,x2_bounds))

# See scipy documentation for additional details about scipy.optimize.OptimizeResult 
# https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.optimize.linprog.html

# Print optimal values of x1, x2, x3 and x4 
print('Scipy Optimize Optimal value:', res.fun, '\n x1, x2:', res.x)
print('\n')

Scipy Optimize Optimal value: -5.4 
 x1, x2: [0.2 1.4]




In [17]:
# https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.optimize.linprog.html

from scipy.optimize import linprog

# coefficients of objective function
z = [-3,-2] 

# coefficients of the left-hand side of the inequalities
lhs = [[1,3],[2,1]]

# coefficients of the right-hand side of the inequalities
rhs = [6, 3]

# set the bounds for the variables
y1_bounds = (0, None)
y2_bounds = (0, None)

method='simplex'

res = linprog(c=z, A_ub=lhs, b_ub=rhs,  bounds=(y1_bounds,y2_bounds))

# See scipy documentation for additional details about scipy.optimize.OptimizeResult 
# https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.optimize.linprog.html

# Print optimal values of x1, x2, x3 and x4 
print('Scipy Optimize Optimal value:', res.fun, '\n y1, y2 :', res.x)
print('\n')

Scipy Optimize Optimal value: -5.4 
 x1, x2 : [0.6 1.8]




In [18]:
27/5


5.4

In [1]:
import numpy
from numpy import *


In [5]:
A = numpy.matrix([[1,3,6],[2,1,3],[3,2,0]])
A_T = numpy.transpose(A)
A_T



matrix([[1, 2, 3],
        [3, 1, 2],
        [6, 3, 0]])

In [48]:
from scipy.optimize import linprog
w = [-5,-24]
lhs = [[4,1],[1,4]]
rhs = [8,8]
y1_bounds = (0,None)
y2_bounds = (0,None)

method = 'simplex'
res = linprog(c=w,A_ub = lhs, b_ub=rhs,bounds = (y1_bounds,y2_bounds))
print('Scipy Optimize Optimal value:',-res.fun,'\n y1, y2 :', res.x)
print('\n slack variables s1, s2', res.slack)

if res.status == 0:
    out = 'Optimization terminated successfully'
elif res.status == 1:
    out = 'Iteration limit reached'
elif res.status == 2:
    out = 'Problem appears to be infeasible'
elif res.status == 3:
    out = 'Problem appears to be unbounded'
elif res.status == 4:
    out = 'Serious numerical difficulties encountered'
print('\n Scipy Optimize Status:', out)

Scipy Optimize Optimal value: 48.0 
 y1, y2 : [0. 2.]

 slack variables s1, s2 [6. 0.]

 Scipy Optimize Status: Optimization terminated successfully


In [67]:
from scipy.optimize import linprog
z = [-60,-67]
lhs = [[2.5,5],[4.5,3],[5,10]]
rhs = [7,9,10]
x1_bounds = (0,None)
x2_bounds = (0,None)


method = 'simplex'
res = linprog(c=z,A_ub = lhs, b_ub=rhs,bounds = (x1_bounds,x2_bounds))
print('Scipy Optimize Optimal value:',-res.fun,'\n x1, x2:', res.x)
print('\n slack variables s1, s2', res.slack)

if res.status == 0:
    out = 'Optimization terminated successfully'
elif res.status == 1:
    out = 'Iteration limit reached'
elif res.status == 2:
    out = 'Problem appears to be infeasible'
elif res.status == 3:
    out = 'Problem appears to be unbounded'
elif res.status == 4:
    out = 'Serious numerical difficulties encountered'
print('\n Scipy Optimize Status:', out)

Scipy Optimize Optimal value: 120.0 
 x1, x2: [2. 0.]

 slack variables s1, s2 [2. 0. 0.]

 Scipy Optimize Status: Optimization terminated successfully


In [68]:
from scipy.optimize import linprog
w = [-7,-9,-10]
lhs = [[2.5,4.5,5],[5,3,10]]
rhs = [60,67]
y1_bounds = (0,None)
y2_bounds = (0,None)
y3_bounds = (0,None)

method = 'simplex'
res = linprog(c=w,A_ub = lhs, b_ub=rhs,bounds = (y1_bounds,y2_bounds,y3_bounds))
print('Scipy Optimize Optimal value:',-res.fun,'\n y1, y2, y3:', res.x)
print('\n slack variables s1, s2', res.slack)

if res.status == 0:
    out = 'Optimization terminated successfully'
elif res.status == 1:
    out = 'Iteration limit reached'
elif res.status == 2:
    out = 'Problem appears to be infeasible'
elif res.status == 3:
    out = 'Problem appears to be unbounded'
elif res.status == 4:
    out = 'Serious numerical difficulties encountered'
print('\n Scipy Optimize Status:', out)

Scipy Optimize Optimal value: 136.20000000000002 
 y1, y2, y3: [8.1        8.83333333 0.        ]

 slack variables s1, s2 [0. 0.]

 Scipy Optimize Status: Optimization terminated successfully


In [64]:
-22.5+(3*2.5)

-15.0

In [65]:
-45+21


-24

In [73]:
from pulp import LpVariable, LpProblem, LpMaximize, LpStatus, value, LpMinimize
#declare your variables
y1 = LpVariable('y1',0,None) # y1>=0
y2 = LpVariable('y2',0,None) # y2>=0
y3 = LpVariable('y3',0,None) # y3>=0
#define the problem
prob = LpProblem('problem',LpMinimize)

#define the constraints
prob += -0.75*y1 + 0.25*y2 + 0.25*y3 <= 0
prob += y2 - (2/3)*y3 >= 0
prob += y1 + y2 + y3 >= 6000
#define the objective function
prob += 9*y1 + 11*y2 + 3*y3

#solve the problem
status = prob.solve()
LpStatus[status]

#Print the results
print("Pulp Solution for y1, y2, & y3")
print(value(y1))
print(value(y2))
print(value(y3))
print('Objective function is: ', 9*value(y1)+11*value(y2)+3*value(y3))

a = value(y1)
b = value(y2)
c = value(y3)

print('\n %Bluegrass: ', (a/(a+b+c)*100))
print('\n rye')

Pulp Solution for y1, y2, & y3
1500.0
1800.0
2700.0
Objective function is:  41400.0


matrix([[ 4,  1,  5],
        [ 1,  4, 24],
        [ 8,  8,  0]])

In [55]:
A = numpy.matrix([[2.5,4.5,5,60],[5,3,10,67],[7,9,10,0]])
A_T = numpy.transpose(A)
A_T

matrix([[ 2.5,  5. ,  7. ],
        [ 4.5,  3. ,  9. ],
        [ 5. , 10. , 10. ],
        [60. , 67. ,  0. ]])

In [58]:
print(265/5)



53.0


In [70]:
49*12

588